{{ config(materialized='table',transient=true)}}

with AMAZON_E_COM as 
(SELECT UNIQ_ID,PRODUCT_NAME,NUMBER_AVAILABLE_IN_STOCK,NUMBER_OF_ANSWERED_QUESTIONS,PRICE,
SUBSTRING(AVERAGE_REVIEW_RATING, 1, CHARINDEX(' ', AVERAGE_REVIEW_RATING) - 1) AS AVERAGE_REVIEW_RATING ,
regexp_replace(NUMBER_OF_REVIEWS, '[^0-9]+', '') AS NUMBER_OF_REVIEWS
FROM PC_DBT_DB.DBT_PSAHU.AMAZON_E_COM2)
select UNIQ_ID,PRODUCT_NAME,NUMBER_OF_ANSWERED_QUESTIONS,AVERAGE_REVIEW_RATING,NUMBER_OF_REVIEWS
,regexp_replace(PRICE, '[^0-9.]+', '') AS PRICE ,regexp_replace(NUMBER_AVAILABLE_IN_STOCK, '[^0-9]+', '') as 
NUMBER_AVAILABLE_IN_STOCK
from AMAZON_E_COM




